apiVersion: v1
kind: Service
metadata:
  name: postmortem-shield
  labels:
    app.kubernetes.io/name: postmortem-shield
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: postmortem-shield
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
